### ISSUE TITLE
domain_valid checking is broken, shows "bad domain syntax" for working domains

### ISSUE THREAD

**Issue by fbettag** [kristapsdz/letskencrypt#10]
Hi there,

nice work on the privsep. Loving it! The only problem seems to be that your domain_valid function has a funky check that prevents some of our domains to not work (but i have working certs from letsencrypt.sh). My private box for example has an issue with 'el8.nl'.

Checking Let's Encrypt certificate status:
letskencrypt: el8.nl: bad domain syntax
Deploying Let's Encrypt certificates:

i believe the registry made the right choice in reference to the RFC :)

thanks

**Comment by kristapsdz** [comment]
Works for me.  Are you using an old version of the system?  Earlier versions checked for isalpha() instead of isalnum().
