### ISSUE TITLE
Missing changelog from source tarball

### ISSUE THREAD

**Issue by Sp1l** [kristapsdz/letskencrypt#11]
There is a changelog on the website, but none in the source repo or tarball.

Please add a file containing the changes to every version to the source repo.

**Comment by kristapsdz** [comment]
I think I'll have this done for the up-coming release via cvs2cl, but will close this out only when it's done.  Thanks for the note!

**Comment by kristapsdz** [comment]
Done!  As of 0.1.10, I have the ChangeLog for both branches in the distributed source.
