### ISSUE TITLE
keep previous certificates

### ISSUE THREAD

**Issue by 22decembre** [kristapsdz/letskencrypt#12]
For various reasons, it can be positive to keep the previous certificates while generating new ones.

For exemple, the new ones could be invalid or buggy, or one want to use DANE, thus needing to wait for DNS propagation.

Currently, letskencrypt store certs at standard place and erase them when generating new ones. There should at least be an option to keep them when creating the new ones.

**Comment by kristapsdz** [comment]
Added in latest set of commits.  Will appear in the next version.
