### ISSUE TITLE
Using with relayd

### ISSUE THREAD

**Issue by mischapeters** [kristapsdz/letskencrypt#14]
Hi,

Any suggestions on how to get letskencrypt going with relayd only on a machine?
There is not really an easy way to point it to the .well-known/acme-challenge/. :(

I have relayd running on one machine and httpd on others. Terminating all SSL centrally on the relayd machine.

Thanx!

Mischa

**Comment by kristapsdz** [comment]
Mish, I'm afraid I don't have anything to advise: I just run a cut-and-dry httpd setup, often using nginx for multiple HTTPS sites (httpd doesn't have SNI).  Try hitting up the relayd folks or asking on the misc mailing list.

**Comment by mischapeters** [comment]
Found a nice work-around: python -m SimpleHTTPServer 80
Or other port and use PF to get it there.
