### ISSUE TITLE
dedicated letskencrypt host

### ISSUE THREAD

**Issue by timkuijsten** [kristapsdz/letskencrypt#18]
First off, I finally found time to test out letskencrypt and I really like it! Awesome work. :)

Some thoughts:
I'd like to have one dedicated openbsd host running letskencrypt and let it handle certificates for all my mail and ubuntu web servers. Since the challenge is directly confirmed to LE as being ready right after it is written to disk, it is currently impossible to scp the challenge files to the ubuntu webhost before LE checks it and fails (although I love `-t` in the meantime ;)

If it would be possible to run an arbitrary shell command in between or maybe let `-C` support arguments like _ssh://user@webserver:/srv/www/example.com/.well-known/acme-challenge_, this setup would be possible. Another route might be to support dns-01.

These are just some first thoughts. I'm new to Let's Encrypt and I'd like to help with a patch if one of these features would make a chance on being incorporated.

~~Related to #14.~~ (something different)

**Comment by kristapsdz** [comment]
Can you try the new (not in a version, just on GH while testing), documented `-t`?  It should solve this problem by letting the shell (or whatever caller) process the thumbprint and token itself:

> An alternate challenge type, however, may be specified with -t, in which case the caller must create the challenge environment.  This may be used for implementing "dns-01" and other system-specific challenges.  To use -t, the caller invoking letskencrypt must wait for the system to print the thumbprint and token as "token.thumbprint\n" (note the a trailing newline) for each domain on standard output.  After each line, the caller must implement the challenge.  Following that, the caller must write the same exact string (along with the newline) as standard input to letskencrypt.  When letskencrypt exits, there are no more domains.

(From the manpage)

**Comment by timkuijsten** [comment]
awesome! I was able to refresh the domain as follows:
`# letskencrypt -Fv -t http-01 example.com`
by manually copy pasting the printed challenge from stdout back to stdin. This allows for some nice scripting :)

**Comment by timkuijsten** [comment]
Just a related note for archival purposes: https://guilhem.org/man/lacme-accountd.1.html via https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827425
