### ISSUE TITLE
change key sizes from 4096 to 2048?

### ISSUE THREAD

**Issue by timkuijsten** [kristapsdz/letskencrypt#20]
Since all certificates are issued by a 2048 bit intermediate certificate. Would it make sense to change the key size from 4096 to 2048 bits? Wouldn't this also make the initial handshake a bit faster?

```
For most web sites, security provided by 2,048-bit RSA keys is
sufficient. The RSA public key algorithm is widely supported, which
makes keys of this type a safe default choice. At 2,048 bits, such
keys provide about 112 bits of security. If you want more security
than this, note that RSA keys don't scale very well. To get 128 bits
of security, you need 3,072-bit RSA keys, which are noticeably slower.
ECDSA keys provide an alternative that offers better security and
better performance. At 256 bits, ECDSA keys provide 128 bits of
security.
```

From: https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices#11-use-2048-bit-private-keys

**Comment by kristapsdz** [comment]
Most (all?) people using the **-N** or **-n** defaults on acme-client won't be using it for high-traffic sites, so I'd rather go with the maximum security at the expense of speed.

**Comment by MasterPuppeteer** [comment]
Can this be made configurable?  Some clients cannot negotiate 4096-bit, ex.
https://github.com/esp8266/Arduino/issues/1375#issuecomment-169519718

Trying to get a similar device to connect securely.  Thank you.
