### ISSUE TITLE
Expanding a certificate with additional SubjectAltNames

### ISSUE THREAD

**Issue by rkrieger** [kristapsdz/letskencrypt#22]
When trying to add an additional SubjectAltName to an existing cert (like certbot's `--expand`), acme-client does not appear to like this change.

For example, adding `test.cluebyfour.nl` to a certificate, acme-client complains.

`# acme-client -bmNv -f /etc/letsencrypt/account-key.pem cluebyfour.nl www.cluebyfour.nl test.cluebyfour.nl`
`acme-client: /etc/ssl/letsencrypt/private/cluebyfour.nl/privkey.pem: domain key exists (not creating)`
`acme-client: /etc/ssl/letsencrypt/cluebyfour.nl/cert.pem: domain not listed: test.cluebyfour.nl`
`acme-client: bad exit: revokeproc(86494): 1`

When I first delete the existing certificate, the command completes fine (i.e. performs a challenge and obtains a cert with the requested SANs).

Proposed fix: create an option `-E` that copes with a domain that is not listed in the current certificate and requests a new certificate with SANs provided on the command line. A patch file to this effect is attached. Do you agree with the approach taken (still emit a warning, but only break out if ' expand == 0' )?

[20161003 acme-client expand.patch.txt](https://github.com/kristapsdz/acme-client/files/506385/20161003.acme-client.expand.patch.txt)

**Comment by kristapsdz** [comment]
I've just merged a form of this patch.  (It also accepts **-e** as the flag, and differs in that it enables forcing the certificate update if an extra field is found.)  Thanks!
