### ISSUE TITLE
sha512 verification does not work

### ISSUE THREAD

**Issue by ston1th** [kristapsdz/letskencrypt#25]
Hi

I tried to verify the hash of the 0.1.14 release.

The .sha512 file contains this: `SHA512(acme-client-0.1.14.tgz)=...`

This command tells me the file is not in the checklist:

```
$ sha512 -C acme-client-0.1.14.sha512 acme-client-0.1.14.tgz 
sha512: acme-client-0.1.14.tgz does not exist in acme-client-0.1.14.sha512
```

Now if I put whitespaces before and after the braces, it works: `SHA512 (acme-client-0.1.14.tgz) =`

```
$ sha512 -C acme-client-0.1.14.sha512 acme-client-0.1.14.tgz 
(SHA512) acme-client-0.1.14.tgz: OK
```

I'm on OpenBSD 6.0 -stable.

**Comment by kristapsdz** [comment]
This will be fixed in the next release.  (It was also pointed out by another user.)  FWIW, I was using openssl dgst instead of sha512.  But I'm now using 512.  Thanks!
