### ISSUE TITLE
no feedback during key generation

### ISSUE THREAD

**Issue by bdijkstra82** [kristapsdz/letskencrypt#27]
Key generation can take a long time on slow hardware. With `-vNn` I would have expected some feedback about what is happening. Perhaps a sequence like this (pseudocode) would be better:
```
log("%s: generating RSA %s key...", file, keytype);
keygen(file, keytype);
log("done.\n");
```

**Comment by kristapsdz** [comment]
Patch?  Having a message span without a newline is a no-no.  But you can add some extra debugging around where the account is being generated, sure.

**Comment by kristapsdz** [comment]
Merged pull request -- thanks!
