### ISSUE TITLE
Challenges are not written - OpenBSD 6.0 -release

### ISSUE THREAD

**Issue by axman6** [kristapsdz/letskencrypt#28]
When running `acme-client -vvNn mydomain.com sub.mydomain.com`, nothing is being written to `/var/www/acme`. No errors are thrown by `acme-client`, but obviously the challenges from Let's Encrypt fail because there's nothing to be served to them. I don't have much to go on, I've done everything mentioned in the man page, all communications with the Let's Encrypt servers seem to be working, but nothing gets written.

**Comment by kristapsdz** [comment]
ls -ld /var/www/acme ?

Other questions: are you using OpenBSD's acme-client or upstream?  More questions, do you see "/var/www/acme/blahblah: created" in the log messages?  Do you see any errors in /var/log/messages when it runs?  Details man, details!

The open() function that writes the challenge will either fail with a warning or succeed with a message.  If there's neither, no challenge has requested itself to be written.  You can give me a lot more information by running the command as you've listed and pasting the entire output here.

**Comment by axman6** [comment]
```# ls -ld /var/www/acme 
drwxr-xr-x  2 root  daemon  512 Jan 28 19:07 /var/www/acme
```

I've tried upstream, it doesn't appear to be in packages. There's nothing in `messages` about acme-client. It does say it's writing the files - I guess they get deleted once the Let's Encrypt API returns? If that's the case, I probably have nginx set up incorrectly.

**Comment by kristapsdz** [comment]
Yes, the challenge files are removed when the prog exits.  If acme-client isn't complaining about anything and Let's Encrypt can't see the file, it's probably in your nginx.  To debug, just put a file into /var/www/acme and see if you can pull it up on the browser.  If you can, reopen this thread with the full results of running acme-client -vv.
