### ISSUE TITLE
No cert.pem / bad exit: netproc(35417)

### ISSUE THREAD

**Issue by nehrwert** [kristapsdz/letskencrypt#34]
I get a strange error, when I try to run acme-client. I can't be sure if it is a bug or if I'm using it wrang, because I don't understand the error. I'm running freebsd and libressl is installed.

acme-client -vNn sitename.de www.sitename.de
acme-client: /usr/local/etc/ssl/acme/private/privkey.pem: generating RSA domain key
acme-client: /etc/ssl/cert.pem: No such file or directory
acme-client: /usr/local/etc/acme/privkey.pem: generating RSA account key
acme-client: adding SAN: www.sitename.de
acme-client: bad exit: netproc(35417): 1

Thank you for your work!

**Comment by kristapsdz** [comment]
It tried (and failed) to find the certificate file to validate its secure communication with the ACME server.  You can set this as the DEFAULT_CA_FILE variable, but you'll need to contact the FreeBSD port administrator (assuming you're using the port) for where the certificate file actually is.
