### ISSUE TITLE
Exit code of 2 when certs are up to date

### ISSUE THREAD

**Issue by lf-** [kristapsdz/letskencrypt#35]
Shouldn't certs being up to date not be an error? Also, if that is why it's returning 2, then there probably should be a message in verbose mode at the very least.

Output:
```
May 21 03:41:36 abyss acme-client[6166]: acme-client: acme-client: acme-client: /etc/acme/privkey.pem: loading RSA account key
May 21 03:41:36 abyss acme-client[6166]: /etc/ssl/acme/cert.pem: certificate valid: 89 days left
May 21 03:41:36 abyss acme-client[6166]: /etc/ssl/acme/private/privkey.pem: loading domain key
May 21 03:41:36 abyss acme-client[6166]: acme-client: /etc/ssl/acme/private/privkey.pem: loaded RSA domain key
May 21 03:41:36 abyss acme-client[6166]: acme-client: adding SAN: www.lfcode.ca
May 21 03:41:36 abyss systemd[1]: acme.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

Version: 0.1.16 on Arch Linux (AUR package version)

**Comment by kristapsdz** [comment]
This is documented in acme-client.1:

> EXIT STATUS
> acme-client returns 1 on failure, 2 if the certificates didn't change (up
> to date), or 0 if certificates were changed (revoked or updated).

And it does warn you in saying "certificate valid: 89 days left".  Is there something else you have in mind?

**Comment by lf-** [comment]
Ah. Failed to find that. Fixed my unit file. Thanks!
