### ISSUE TITLE
acme-client: bad exit: netproc(15)

### ISSUE THREAD

**Issue by u007** [kristapsdz/letskencrypt#43]
hi 
where can i see list of netproc errors?

**Comment by dch** [comment]
u007 re-run your acme-clientr with `-vv` flags to see what actually failed. the netproc is just one of the subsidiary processes dying for some reason.

**Comment by Sebbyastian** [comment]
root@expression:/home/Seb # acme-client -vvNn expression.network
    acme-client: /usr/local/etc/acme/privkey.pem: account key exists (not creating)
    acme-client: /usr/local/etc/ssl/acme/private/privkey.pem: domain key exists (not creating)
    acme-client: tls_init: No error: 0
    acme-client: /usr/local/etc/acme/privkey.pem: loading RSA account key
    acme-client: /usr/local/etc/ssl/acme/private/privkey.pem: loading domain key
    acme-client: /usr/local/etc/ssl/acme/private/privkey.pem: loaded RSA domain key
    acme-client: bad exit: netproc(37526): 1

It seems to be the first and only subprocess that's failing here.

**Comment by Sebbyastian** [comment]
I also wish to answer the question in the body here, after reviewing the codebase for this project... there's no _error number_ here to look up in a _list of netproc errors_, so really the question makes no sense.

> where can i see list of netproc errors?

Consider the first number you see in my error message, this one here:

> acme-client: bad exit: netproc(**37526**): 1

That is a **process ID**, so it's not something you can look up. The other number, which is 1, is what the process `main` entry point returned (i.e. `exit(1)`). 1 is a very generic failure value. You don't actually get given a reason for _netproc failure_. It's feral.

The error reporting system for this project is disgusting, so I did what I usually do for disgusting projects, contributed my bit to make the project as a whole a little bit less disgusting, and now I'm moving on. I suggest you do likewise, and choose one of the many alternatives that don't use curl.

**Comment by desnudopenguino** [comment]
```
# acme-client -vvnNFm dev.yacfr.com                                                                                   
acme-client: /etc/acme/dev.yacfr.com/privkey.pem: account key exists (not creating)                                   
acme-client: /etc/ssl/acme/private/dev.yacfr.com/privkey.pem: domain key exists (not creating)                        
acme-client: acme-client: /etc/acme/dev.yacfr.com/privkey.pem: loading RSA account key                                
/etc/ssl/acme/private/dev.yacfr.com/privkey.pem: loading domain key
acme-client: /etc/ssl/acme/private/dev.yacfr.com/privkey.pem: loaded RSA domain key                                   
acme-client: https://acme-v01.api.letsencrypt.org/directory: directories                                              
acme-client: acme-v01.api.letsencrypt.org: DNS: 23.195.232.123                                                        
acme-client: acme-v01.api.letsencrypt.org: DNS: 2600:1409:5000:28e::3a8e                                              
acme-client: acme-v01.api.letsencrypt.org: DNS: 2600:1409:5000:283::3a8e                                              
acme-client: transfer buffer: [{ "Uu20YJa0tbg": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417", "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change", "meta": { "caaIdentities": [ "letsencrypt.org" ], "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf", "website": "https://letsencrypt.org" }, "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz", "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert", "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg", "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert" }] (658 bytes)
acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: dev.yacfr.com
acme-client: acme-v01.api.letsencrypt.org: cached
acme-client: acme-v01.api.letsencrypt.org: cached                                                                     
acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: bad HTTP: 403                                       
acme-client: transfer buffer: [{ "type": "urn:acme:error:unauthorized", "detail": "No registration exists matching provided key", "status": 403 }] (120 bytes)
acme-client: bad exit: netproc(80934): 1
```

This is what I get on FreeBSD 11.2-RELEASE I've tried with the pkg, port, and manual installs and get the same thing.  All 3 versions appear to be 0.1.16 as well. On FreeBSD 11.1p4, acme-client from pkg is working fine. I'm not sure what changed in between, but it's quite frustrating.

**Comment by desnudopenguino** [comment]
```
# acme-client -vvnNFm my.domain.com
acme-client: /etc/acme/my.domain.com/privkey.pem: account key exists (not creating)
acme-client: /etc/ssl/acme/private/my.domain.com/privkey.pem: domain key exists (not creating)
acme-client: acme-client: /etc/acme/my.domain.com/privkey.pem: loading RSA account key 
/etc/ssl/acme/private/my.domain.com/privkey.pem: loading domain key 
acme-client: /etc/ssl/acme/private/my.domain.com/privkey.pem: loaded RSA domain key 
acme-client: https://acme-v01.api.letsencrypt.org/directory: directories
acme-client: acme-v01.api.letsencrypt.org: DNS: 23.195.232.123
acme-client: acme-v01.api.letsencrypt.org: DNS: 2600:1409:5000:28e::3a8e
acme-client: acme-v01.api.letsencrypt.org: DNS: 2600:1409:5000:283::3a8e
acme-client: transfer buffer: [{ "Uu20YJa0tbg": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417", "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change", "meta": { "caaIdentities": [ "letsencrypt.org" ], "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf", "website": "https://letsencrypt.org" }, "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz", "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert", "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg", "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert" }] (658 bytes)
acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: my.domain.com
acme-client: acme-v01.api.letsencrypt.org: cached
acme-client: acme-v01.api.letsencrypt.org: cached
acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: bad HTTP: 403 
acme-client: transfer buffer: [{ "type": "urn:acme:error:unauthorized", "detail": "No registration exists matching provided key", "status": 403 }] (120 bytes)
acme-client: bad exit: netproc(80934): 1
```

On FreeBSD 11.2-RELEASE (provided via Vultr web hosting). It (acme-client) from pkg appears to be working fine on FreeBSD 11.1p4 though. On 11.2, I'm getting the same or similar errors from the pkg, ports, and manual install methods.

```
# acme-client -vvnNFm my.domain.com
acme-client: /usr/local/etc/acme/my.domain.com/privkey.pem: account key exists (not creating)
acme-client: /usr/local/etc/ssl/acme/private/my.domain.com/privkey.pem: domain key exists (not creating)
acme-client: tls_init: No error: 0
acme-client: /usr/local/etc/ssl/acme/private/my.domain.com/privkey.pem: loading domain key
acme-client: /usr/local/etc/ssl/acme/private/my.domain.com/privkey.pem: loaded RSA domain key
acme-client: /usr/local/etc/acme/my.domain.com/privkey.pem: loading RSA account key                                    
acme-client: bad exit: netproc(81040): 1
```

is from pkg, the above is from ports or manual install (downloading the tgz from acme-client's site)

**Comment by Sebbyastian** [comment]
Okay, since I'm notified of these responses I thought I'd give a little bit more than just some token advice... often when I'm prototyping I'll write code like this (after `#include`ing `<assert.h>`):

```
int x = fscanf(stdin, "%d %d", &fu, &ba);
assert("some invalid input or eof occured?" && x == 2);
```

The unfortunate part about this example is it's an edgecase; you might never notice the bugs unless you're looking for them in debug mode, but at least you'll find them in debug mode... for most cases, this kind of code not only validates your logic as you run it (and write it) but also documents your intention for others.

In some places you might have something similar... but you need some better message than "bad exit" with a failure of 1, that much is clear!

**Comment by flipchan** [comment]
i got a similar errorb

``
mail# acme-client -vv mail.example.com                      
acme-client: acme-client: acme-client: /etc/ssl/private/mail.example.com.key: loaded RSA domain key/etc/acme/letsencrypt-privkey.pem: loaded RSA account key/etc/ssl/mail.example.com.crt: certificate renewable: 0 days left


acme-client: https://acme-v02.api.letsencrypt.org/directory: directories
acme-client: acme-v02.api.letsencrypt.org: DNS: 23.78.50.200
acme-client: https://acme-v02.api.letsencrypt.org/directory: bad CA paths
acme-client: transfer buffer: [{ "cKI75QkHOYo": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417", "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change", "meta": { "caaIdentities": [ "letsencrypt.org" ], "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf", "website": "https://letsencrypt.org" }, "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct", "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce", "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order", "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert" }] (658 bytes)
acme-client: bad exit: netproc(52794): 1


``

**Comment by flipchan** [comment]
i solved it by changing the urls from letsencrypts v2 api to the v1 api url in the conf file
