### ISSUE TITLE
What is the equivalent command for letsencrypt-auto tool?

### ISSUE THREAD

**Issue by tfarina** [kristapsdz/letskencrypt#6]
Hi,

What is the equivalent letskencrypt command for the following command line?

$ letsencrypt-auto certonly --standalone -d mydomain.com

**Comment by kristapsdz** [comment]
I don't know---I've never used letsencrypt-auto.  The [letskencrypt(1)](https://kristaps.bsd.lv/letskencrypt/letskencrypt.1.html) manpage will tell you its usage.

**Comment by tfarina** [comment]
The problem I'm facing is that it says 'privkey.pem' file must exist. But it does not say how I should generate it.

**Comment by tfarina** [comment]
This is the command I'm running:

$ sudo LD_LIBRARY_PATH=/usr/local/lib ./letskencrypt -m mydomain.com
letskencrypt: /etc/ssl/letsencrypt/mydomain.com: -c directory must exist
letskencrypt: /etc/ssl/letsencrypt/private/mydomain.com/privkey.pem: -k file must exist
letskencrypt: /var/www/letsencrypt: -C directory must exist
letskencrypt: /etc/letsencrypt/mydomain.com/privkey.pem: -f file must exist

**Comment by star26bsd** [comment]
same here.

**Comment by kristapsdz** [comment]
Does the new [letskencrypt(1)](https://github.com/kristapsdz/letskencrypt/blob/master/letskencrypt.1) address this in its EXAMPLES?  In short, you must create all directories and files unless -n is passed, in which case the account key (**not** the domain key) is created.  Usually, keys are created with the openssl(1) command, as now noted in the example.

Is it normal behaviour for the other letsencrypt clients to create the domain key if requested?

**Comment by star26bsd** [comment]
I don't know how other letsencrypt clients work. This is my first attempt to get it all running, since I was waiting for a small, tiny and secure client for OpenBSD first :) I do appreciate the new EXAMPLES section.

**Comment by kristapsdz** [comment]
The **-N** flag in the latest release will also do this.  Thanks!

**Comment by tfarina** [comment]
Thank you! I will try again, because yesterday it didn't work.
