### ISSUE TITLE
Idempotence

### ISSUE THREAD

**Issue by problame** [kristapsdz/letskencrypt#8]
Thank you for developing `letskencrypt`, it has become my preferred way of using Let's Encrypt.

However, you might want to consider redesigning the error-behavior of flags such as `-n` and `-N`.

Example: if `-n` and `-N` did not fail but were a _noop_ if the domain / account key already exists, there would not be a need for special-casing this in automatic deployments (shell scripts, Ansible modules, ...).

Have you considered this aspect already? I would like to know your opinion on this topic.

**Comment by kristapsdz** [comment]
@problame, that's a good idea---it makes sense.  I'll put it in.

**Comment by problame** [comment]
👍 any chance auto creation of directories could be added alongside this feature? `-m` is still annoying otherwise...

**Comment by kristapsdz** [comment]
This has been added in the last set of github checkins.  (You still need to create the root directories, e.g., /var/www/acme, /etc/acme, /etc/ssl/acme, etc.)  Thanks!
